### ISSUE TITLE
[Bug] Adapter and LoRA for Roberta 

### ISSUE THREAD

**Issue by Albert-Ma** [jxhe/unify-parameter-efficient-tuning#16]
Runing the below setting on SST2 and MNLI:
`attn_mode="adapter"
attn_option="sequential"
attn_composition="add"
attn_bn=200  # attn bottleneck dim

 ffn_mode="adapter"
ffn_option="sequential"
 ffn_adapter_layernorm_option="none"
 ffn_adapter_init_option="bert"
 ffn_adapter_scalar="1"
 ffn_bn=200 # ffn bottleneck dim
`

Several errors were raised. It seems some parameters were set incorrectly like `d_model`, `dropout`, in modeling_roberta.py.

I just fix them and the log make me confused:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/7343136/159874934-03fafaa2-4a78-4bb8-9b27-3cac4cb39fcf.png">

Houlsby added adapted in two places: after self-attention and after FFN.
So why add Adapter inside the self-attention and what's the adapter_layer_norm_before.weight used for?

Thanks

**Comment by Albert-Ma** [comment]
For LoRA:
`attn_mode="lora"
attn_option="parallel"
attn_composition="add"
attn_bn=200  # attn bottleneck dim

ffn_mode="none"
ffn_option="parallel"
ffn_adapter_layernorm_option="none"
ffn_adapter_init_option="lora"
ffn_adapter_scalar="4"
ffn_bn=512 # ffn bottleneck dim`

File "unify-parameter-efficient-tuning-master/src/transformers/models/roberta/modeling_roberta.py", line 213, in __init__
    raise ValueError("att_mode not supported")
ValueError: att_mode not supported

**Comment by jxhe** [comment]
Thank you for catching those bugs! Those syntax errors on roberta and lora have been fixed in the latest version, and the new README contains the config to run the LoRA approach, please pull the change and try again. Regarding your questions:

1. *Why is Houlsby adapter inside the self-attention?* It is not,  the Houlsby adapters are actually only added in block 2 and 3 in your screenshots (i.e. `layer.attention.output` and `layer.output`). The adapters in block 1 (`layer.attention.self`) were added for parallel adapters, but they are not being used in your config setting: https://github.com/jxhe/unify-parameter-efficient-tuning/blob/3222ce2c0079566a28043e22380eb4ab6ad14389/src/transformers/models/roberta/modeling_roberta.py#L337

2. *What's adapter_layer_norm_before.weight for?* In the original Houlsby adapters, they fine-tune the adapter weights along with the **original transformer layer norm parameters** (this can be found in their paper). Many later re-implementations chose to add additional layernorm before adapters, fine-tune the added layernorm parameters, but freeze the original layernorms.  Here we implemented the later, i.e. `adapter_layer_norm_before.weight` is the weight of the added layernorm before attention adapters.

**Comment by Albert-Ma** [comment]
Thanks for your reply！

1) I found the classifier layer which is on top of the pre-trained model, is only initialized and never trained. But it still got a high performance, so just curious about the reason.
When unfreezing this layer during training, the performance got slightly improvement.
2) The training speed and the GPU memory footprint got just x1 speedup and decrease about 1-3 times, respectively, in my server. Is this right?
In addition to only storing parameters of a large model and several small modules for multiple tasks, are there other potential advantages of effective parameter tuning?

**Comment by jxhe** [comment]
1. We never tried tuning the classifier head but training it sounds like a reasonably cheap trick that should give higher performance. I am not sure about the reason, I guess that it is easy to learn features that can be separated by a random projection given that both MNLI and SST2 are just two- or three-way classification.

2. The main advantage or the most intriguing part of parameter-efficient tuning is not about reducing the training cost -- it doesn't really reduce the training cost much since it often takes longer to converge. In my opinion, the advantages are:   
  (1) storage savings as you mentioned; 
  (2) more interestingly, it has potentials on multi-task settings -- one small module is responsible for one task/domain while most of the parameters are shared, this separates model capacities in a modular way and may enable many applications, for example, merging multiple adapters efficiently to create models that perform well on multiple domains; continuously adding new capabilities without breaking original capabilities to an existing system by just adding trained adapters. These may not be achieved easily by traditional fine-tuning.
  (3) parameter-efficient tuning mitigates catastrophic forgetting by design since old parameters are frozen.
  (4) tuning few parameters is also shown in some papers to be more robust than full fine-tuning and is superior for few-shot learning

**Comment by Albert-Ma** [comment]
Thanks for your kind reply!

**Comment by Albert-Ma** [comment]
By the way, the prompt tuning setting also cannot work either on two glue tasks. @jxhe 
`----- Prompt Tuning -----
 attn_mode="prompt_tuning"
 attn_option="parallel"
 attn_composition="add"
 attn_bn=200  # attn bottleneck dim

 ffn_mode="none"
 ffn_option="parallel"
 ffn_adapter_layernorm_option="none"
 ffn_adapter_init_option="lora"
 ffn_adapter_scalar="4"
 ffn_bn=512 # ffn bottleneck dim`
